spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/order?useSSL=false
    username: root
